---
output:
  word_document: default
  html_document: default
---
# Model Validation Assignment
## Huffman, Abigail  

```{r include=FALSE}
library(tidyverse)
library(tidymodels)
library(lubridate)

bike <- read_csv("bike_cleaned-2.csv")
bike = bike %>% mutate(dteday = mdy(dteday)) 
bike = bike %>% mutate_if(is.character,as_factor)
bike = bike %>% mutate(hr = as_factor(hr))
```

```{r Task 1}
set.seed(1234)
bike_split = initial_split(bike, prob = 0.0, strata = count)
train = training(bike_split)
test = testing(bike_split)
```  

**The test set has 4343 rows and the training set has 13036 rows.**  

```{r}
bike_recipe = recipe(count ~ season + mnth + hr + holiday + weekday + temp + weathersit, train)

lm_model =
  linear_reg() %>% 
  set_engine("lm") 

lm_wflow = 
  workflow() %>% 
  add_model(lm_model) %>% 
  add_recipe(bike_recipe)

lm_fit = fit(lm_wflow, train)
```


```{r}
summary(lm_fit$fit$fit$fit)
```

```{r}
predict_train <- predict(lm_fit, train)

ggplot(predict_train,aes(x=.pred)) + geom_histogram() +theme_bw()
```
  
**The distribution is fairly even, but a bit skewed in the center of the histogram.**  

```{r}
lm_fit %>% predict(test) %>% bind_cols(test) %>% metrics(truth = count, estimate = .pred)
```
  
**The R squared on the testing set went down slightly but did not show a large decrease. I am not alarmed and feel this must be a pretty good model.**